// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (b *Book) User(ctx context.Context) (*User, error) {
	result, err := b.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = b.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Books(ctx context.Context) (result []*Book, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedBooks(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.BooksOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryBooks().All(ctx)
	}
	return result, err
}
